



# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 8
buffer_size: 5000
batch_size: 128

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "updet_mac"
agent: "updeept_agent"

agent_output_type: q
# %%%%%%%%%%%%% Transformer Settings %%%%%%%%%%%
transformer_embed_dim: 32
moe_inter_dim: 64
n_routed_experts: 3
n_shared_experts: 1
n_activated_experts:  1
n_expert_groups:  1
n_limited_groups:  1
transformer_heads: 3  # head number of transformer
transformer_depth: 2  # block number of transformer
use_moe: True

learner: "nq_learner"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
td_lambda: 0.6
optimizer: 'adam'
q_lambda: False

use_wandb: False

name: "updeept_qmix_64_3_no_gate"

score_func: "softmax"

############# others
route_scale: 1.0
rope_theta: 10000.0
rope_factor: 40
beta_fast: 32
beta_slow: 1
mscale: 1.0

transfer: False
evaluate: False
moe_coef: 0.001
bias_gamma: 0.01
gate: 'gate_v3'
freeze: "none"
# keep_experts: [0,1]
n_additional_experts: 0
# checkpoint_path: "/home/marl2024/DeepSeekHPN/results/models/sc2_3s_vs_3z-obs_aid=1-obs_act=1/algo=updeept_qmix_64_3 -agent=updeept_agent/env_n=8/rnn_dim=64-2bs=5000_128-tdlambda=0.6-epdec_0.05=100k/updeept_qmix_64_3 __2025-05-04_11-53-07"